name       : davmail
version    : 6.1.0
release    : 4
source     :
    - https://sourceforge.net/projects/davmail/files/davmail/6.1.0/davmail-src-6.1.0-3423.tgz : 08e7103d14e9f05ec269caceef7585dcf8be202a35c471fa6fc12729cf99ef2f
homepage   : http://davmail.sourceforge.net
license    : GPL-2.0-or-later
component  : network.mail
summary    : DavMail POP/IMAP/SMTP/Caldav/Carddav/LDAP Exchange and Office 365 Gateway
description: |
    DavMail is a POP/IMAP/SMTP/Caldav/Carddav/LDAP Exchange and Office 365 Gateway allowing users to use any mail/calendar client (e.g. Thunderbird with Lightning or Apple iCal) with an Exchange server, even from the internet or behind a firewall through Outlook Web Access. DavMail now includes an LDAP gateway to Exchange global address book and user personal contacts to allow recipient address completion in mail compose window and full calendar support with attendees free/busy display.
networking : true
builddeps  :
    - apache-ant
    - openjdk-17
rundeps    :
    - openjdk-17
build      : |
    JAVA_HOME=/usr/lib64/openjdk-17 ant
install    : |
    install -dm00644 $installdir/usr/share/davmail/lib
    unzip -q $(find dist/ -name "davmail-*-trunk.zip" -type f) -d source/
    install -m00644 source/lib/* $installdir/usr/share/davmail/lib/
    install -m00644 source/davmail.jar $installdir/usr/share/davmail/
    install -Dm00644 src/icon/davmail.png $installdir/usr/share/icons/hicolor/128x128/apps/davmail.png
    install -Dm00644 src/desktop/davmail.desktop $installdir/usr/share/applications/davmail.desktop
    install -Dm00644 src/appstream/org.davmail.DavMail.appdata.xml $installdir/usr/share/metainfo/org.davmail.DavMail.appdata.xml

    # Install custom executable file with proper path of execute
    install -Dm00755 $pkgfiles/davmail $installdir/usr/bin/davmail
